import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { User, AtSign, CheckCircle2, XCircle, Loader } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';

export default function OnboardingPage() {
  const navigate = useNavigate();
  const { user, profile, refreshProfile, signOut } = useAuth();

  const [fullName, setFullName]   = useState(profile?.full_name || '');
  // Prefill username only if it doesn't look auto-generated (auto ones look like "johndoe_a1b2c3")
  const isAutoGenerated = (u?: string) => !u || /_[0-9a-f]{6}$/.test(u);
  const [username, setUsername]   = useState(isAutoGenerated(profile?.username) ? '' : profile?.username || '');
  const [status, setStatus]       = useState<'idle' | 'checking' | 'available' | 'taken' | 'invalid'>('idle');
  const [loading, setLoading]     = useState(false);
  const [error, setError]         = useState('');

  const checkAvailability = useCallback(async (value: string) => {
    if (value.length < 3) { setStatus('invalid'); return; }
    if (!/^[a-zA-Z0-9_]+$/.test(value)) { setStatus('invalid'); return; }

    // If the user already owns exactly this username, it's always valid for them
    if (profile?.username?.toLowerCase() === value.toLowerCase()) {
      setStatus('available');
      return;
    }

    setStatus('checking');
    const { data } = await supabase
      .from('profiles')
      .select('id')
      .eq('username', value.toLowerCase())
      .maybeSingle();

    setStatus(data ? 'taken' : 'available');
  }, [profile?.username]);

  useEffect(() => {
    if (!username) { setStatus('idle'); return; }
    const timer = setTimeout(() => checkAvailability(username), 400);
    return () => clearTimeout(timer);
  }, [username, checkAvailability]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;

    const trimmedName = fullName.trim();
    if (trimmedName.length < 2) {
      setError('Display name must be at least 2 characters');
      return;
    }
    if (status !== 'available') {
      setError('Please enter a valid, available username');
      return;
    }

    setLoading(true);
    setError('');

    const { error: updateError } = await supabase
      .from('profiles')
      .update({
        full_name: trimmedName,
        username:  username.toLowerCase(),
      })
      .eq('id', user.id);

    setLoading(false);

    if (updateError) {
      setError(updateError.message);
      return;
    }

    await refreshProfile();
    navigate('/');
  };

  // ── Status indicator helpers ──────────────────────────────────────────────
  const statusIcon = () => {
    if (status === 'checking') return <Loader size={16} style={{ animation: 'spin 0.8s linear infinite' }} />;
    if (status === 'available') return <CheckCircle2 size={16} color="#22D3EE" />;
    if (status === 'taken' || status === 'invalid') return <XCircle size={16} color="#F87171" />;
    return null;
  };

  const statusMsg = () => {
    if (status === 'available') return <span style={{ color: '#22D3EE', fontSize: '0.8rem' }}>✓ Username is available</span>;
    if (status === 'taken')     return <span style={{ color: '#F87171', fontSize: '0.8rem' }}>✗ This username is taken</span>;
    if (status === 'invalid')   return <span style={{ color: '#F87171', fontSize: '0.8rem' }}>✗ 3–20 chars, letters / numbers / underscores only</span>;
    return null;
  };

  return (
    <div className="auth-page">
      <div className="auth-card animate-slide-up">

        {/* Logo */}
        <div className="auth-logo">
          <div className="auth-logo-icon">
            <svg width="22" height="22" viewBox="0 0 24 24" fill="white">
              <path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2z"/>
            </svg>
          </div>
          <span className="auth-logo-text">MKP Chat</span>
        </div>

        {/* Heading */}
        <h1 className="auth-title">Complete your profile</h1>
        <p className="auth-subtitle">Choose a display name and username to start chatting</p>

        {/* Step progress indicator */}
        <div style={{ display: 'flex', justifyContent: 'center', gap: 8, marginBottom: 24 }}>
          {[1, 2, 3].map(n => (
            <div key={n} style={{
              width: n === 2 ? 24 : 8, height: 8, borderRadius: 4,
              background: n === 2 ? 'var(--color-primary)' : 'var(--color-border)',
              transition: 'all 0.3s',
            }} />
          ))}
        </div>

        {error && <div className="error-box" style={{ marginBottom: 16 }}>{error}</div>}

        <form onSubmit={handleSubmit} className="auth-form">

          {/* Display Name */}
          <div className="input-group">
            <label htmlFor="onbrd-name" className="input-label">Display Name</label>
            <div className="input-wrapper">
              <input
                id="onbrd-name"
                type="text"
                className="input"
                placeholder="e.g. John Doe"
                value={fullName}
                onChange={e => setFullName(e.target.value)}
                maxLength={60}
                required
                style={{ paddingLeft: 44 }}
              />
              <span className="input-icon" style={{ left: 12 }}><User size={16} /></span>
            </div>
            <div style={{ minHeight: 18, fontSize: '0.78rem', color: 'var(--color-text-muted)' }}>
              This is shown to everyone in chat
            </div>
          </div>

          {/* Username */}
          <div className="input-group">
            <label htmlFor="onbrd-username" className="input-label">Username</label>
            <div className="input-wrapper">
              <input
                id="onbrd-username"
                type="text"
                className="input"
                placeholder="e.g. john_doe"
                value={username}
                onChange={e => setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, ''))}
                maxLength={20}
                required
                style={{ paddingLeft: 44, paddingRight: 44 }}
              />
              <span className="input-icon" style={{ left: 12 }}><AtSign size={16} /></span>
              <span className="input-icon">{statusIcon()}</span>
            </div>
            <div style={{ minHeight: 20 }}>{statusMsg()}</div>
          </div>

          <button
            type="submit"
            className="btn btn-primary btn-full btn-lg"
            disabled={loading || status === 'taken' || status === 'invalid' || status === 'idle' || status === 'checking'}
          >
            {loading
              ? <><span className="loader" style={{ width: 18, height: 18, borderWidth: 2 }} /> Saving...</>
              : 'Continue to Chat →'
            }
          </button>
        </form>

        {/* Sign out */}
        <div style={{ marginTop: 20, textAlign: 'center' }}>
          <button
            onClick={async () => { await signOut(); navigate('/login'); }}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              fontSize: '0.8125rem', color: 'var(--color-text-muted)',
            }}
          >
            Sign out
          </button>
        </div>

      </div>
    </div>
  );
}
